### PR TITLE
examples images moved to examples directory

### LINKED ISSUE #14: Move example images to examples directory

### PR DESCRIPTION
**Pull request by Rishav1707**
## This PR closes the following issue:
closes #14

### CODE REVIEW

**Comment by AsaiToshiya** [comment]
Thank you for the PR @Rishav1707.

You don't need to change index.js.

**Comment by Rishav1707** [comment]
> Thank you for the PR @Rishav1707.
> 
> You don't need to change index.js.

Ok I'll change it and report to you soon

**Comment by Rishav1707** [comment]
> Thank you for the PR @Rishav1707.
> 
> You don't need to change index.js.

Done

**Comment by AsaiToshiya** [comment]
Thank you @Rishav1707.

**Pull request merged**
